# Generated by Django 5.0.6 on 2025-08-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupactivity',
            name='classroom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupactivity',
            name='location_type',
            field=models.CharField(choices=[('on_campus', '校內'), ('off_campus', '校外')], default='on_campus', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupactivity',
            name='type',
            field=models.CharField(choices=[('food', '美食'), ('sport', '運動'), ('study', '讀書'), ('travel', '旅遊'), ('movie', '電影'), ('other', '其他')], max_length=50),
        ),
    ]
