# Generated by Django 4.2.6 on 2025-08-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('CS', '資訊系'), ('EE', '電機系'), ('ME', '機械系')], max_length=50)),
                ('grade', models.CharField(choices=[('1', '一年級'), ('2', '二年級'), ('3', '三年級'), ('4', '四年級')], max_length=10)),
                ('book_type', models.CharField(choices=[('textbook', '教科書'), ('reference', '參考書'), ('novel', '小說')], max_length=50)),
                ('condition', models.CharField(choices=[('new', '全新'), ('good', '良好'), ('used', '二手')], max_length=50)),
                ('transaction', models.CharField(choices=[('face', '面交'), ('mail', '郵寄')], max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
