# Generated by Django 5.0.6 on 2025-08-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityparticipant',
            options={'verbose_name': '活動參與者', 'verbose_name_plural': '活動參與者'},
        ),
        migrations.AlterModelOptions(
            name='groupactivity',
            options={'ordering': ['-created_at'], 'verbose_name': '團體活動', 'verbose_name_plural': '團體活動'},
        ),
    ]
