# Generated by Django 5.2 on 2025-09-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0002_groupactivity_location_type_alter_groupactivity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursereview",
            name="is_anonymous",
            field=models.BooleanField(default=True),
        ),
    ]
