# Generated by Django 5.0.6 on 2025-09-04 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_groupactivity_classroom_groupactivity_location_type_and_more'),
        ('web_app', '0002_groupactivity_location_type_alter_groupactivity_type'),
    ]

    operations = [
    ]
