# Generated by Django 4.2.6 on 2025-08-26 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_alter_activityparticipant_options_and_more'),
        ('web_app', '0002_book'),
    ]

    operations = [
    ]
