# Generated by Django 5.0.6 on 2025-09-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_coursereview_is_anonymous'),
        ('web_app', '0003_merge_20250904_1248'),
    ]

    operations = [
    ]
