# Generated by Django 4.2.6 on 2025-08-26 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0003_merge_20250826_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activityparticipant',
            options={},
        ),
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('grade', models.IntegerField()),
                ('condition', models.CharField(choices=[('new', '全新'), ('good', '良好'), ('used', '尚可')], max_length=10)),
                ('other', models.CharField(blank=True, help_text='多選，逗號分隔', max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book2_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_app.academic')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_app.category')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book2_contact', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_app.department')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book2_seller', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web_app.status')),
            ],
        ),
    ]
