# Generated by Django 5.0.6 on 2025-09-28 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_merge_20250914_1717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'web_app_ReviewLike',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursestar',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='coursestar',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursestar',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='coursereview',
            options={'managed': False, 'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='groupactivity',
            name='classroom',
        ),
        migrations.AddField(
            model_name='book2',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book2',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book2',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_activity_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitycomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_activity_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book2',
            name='grade',
            field=models.ForeignKey(blank=True, db_column='grade_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='web_app.academicgrade'),
        ),
        migrations.AlterField(
            model_name='book2',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status_id', default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='web_app.status'),
        ),
        migrations.AlterField(
            model_name='groupactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_activities_created', to=settings.AUTH_USER_MODEL, verbose_name='發起者'),
        ),
        migrations.AlterField(
            model_name='status',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='activitycomment',
            index=models.Index(fields=['activity', 'created_at'], name='idx_cmt_activity_created'),
        ),
        migrations.AddIndex(
            model_name='activityparticipant',
            index=models.Index(fields=['activity', 'user'], name='idx_part_activity_user'),
        ),
        migrations.AddIndex(
            model_name='activityparticipant',
            index=models.Index(fields=['status'], name='idx_part_status'),
        ),
        migrations.AddIndex(
            model_name='groupactivity',
            index=models.Index(fields=['date', 'time'], name='idx_ga_dt'),
        ),
        migrations.AddIndex(
            model_name='groupactivity',
            index=models.Index(fields=['type'], name='idx_ga_type'),
        ),
        migrations.AddIndex(
            model_name='groupactivity',
            index=models.Index(fields=['location_type'], name='idx_ga_loctype'),
        ),
        migrations.AlterModelTable(
            name='book2',
            table='web_app_book2',
        ),
        migrations.DeleteModel(
            name='CourseStar',
        ),
    ]
