# Generated by Django 4.2.6 on 2025-08-26 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_academic_category_department_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book2',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='web_app.status'),
        ),
    ]
