# Generated by Django 4.2.6 on 2025-08-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_alter_book2_status'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='book2',
        #     name='other',
        # ),
    ]
