# Generated by Django 4.2.6 on 2025-08-27 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_remove_book2_other'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='book2',
        #     name='other',
        # ),
        migrations.AlterField(
            model_name='book2',
            name='academic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web_app.academic'),
        ),
        migrations.AlterField(
            model_name='book2',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web_app.category'),
        ),
        migrations.AlterField(
            model_name='book2',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web_app.department'),
        ),
        migrations.AlterField(
            model_name='book2',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='web_app.status'),
        ),
    ]
