# Generated by Django 4.2.6 on 2025-08-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_remove_book2_other_alter_book2_academic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book2',
            name='other',
        ),
        migrations.AlterField(
            model_name='book2',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', '全新'), ('good', '良好'), ('used', '尚可')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='book2',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
