# Generated by Django 5.2 on 2025-08-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0008_remove_book2_other_alter_book2_condition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "web_app_course", "managed": False,},
        ),
        migrations.CreateModel(
            name="Departmentd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"db_table": "department", "managed": False,},
        ),
    ]
