# Generated by Django 5.2 on 2025-08-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0009_course_departmentd"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcadeDepart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "academic_department", "managed": False,},
        ),
        migrations.CreateModel(
            name="AcadeGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_level", models.CharField(max_length=50)),
            ],
            options={"db_table": "academic_grade", "managed": False,},
        ),
        migrations.CreateModel(
            name="Academica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"db_table": "academic", "managed": False,},
        ),
    ]
