# Generated by Django 5.2 on 2025-08-29 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcadeDepart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "academic_department", "managed": False,},
        ),
        migrations.CreateModel(
            name="AcadeGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade_level", models.CharField(max_length=50)),
            ],
            options={"db_table": "academic_grade", "managed": False,},
        ),
        migrations.CreateModel(
            name="Academic",
            fields=[
                (
                    "id",
                    models.CharField(max_length=1, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"db_table": "academic", "managed": False,},
        ),
        migrations.CreateModel(
            name="Academica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"db_table": "academic", "managed": False,},
        ),
        migrations.CreateModel(
            name="AcademicGrade",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("grade_level", models.CharField(max_length=50)),
            ],
            options={"db_table": "academic_grade", "managed": False,},
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("grade_level", models.CharField(max_length=50)),
                ("course_id", models.CharField(max_length=50)),
                ("course_name", models.CharField(max_length=50)),
                ("course_teacher", models.CharField(max_length=50)),
            ],
            options={"db_table": "web_app_course", "managed": False,},
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"db_table": "department", "managed": False,},
        ),
        migrations.CreateModel(
            name="Departmentd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={"db_table": "department", "managed": False,},
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.TextField(blank=True)),
                (
                    "department",
                    models.CharField(
                        choices=[("CS", "資訊系"), ("EE", "電機系"), ("ME", "機械系")],
                        max_length=50,
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("1", "一年級"),
                            ("2", "二年級"),
                            ("3", "三年級"),
                            ("4", "四年級"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "book_type",
                    models.CharField(
                        choices=[
                            ("textbook", "教科書"),
                            ("reference", "參考書"),
                            ("novel", "小說"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "全新"), ("good", "良好"), ("used", "二手")],
                        max_length=50,
                    ),
                ),
                (
                    "transaction",
                    models.CharField(
                        choices=[("face", "面交"), ("mail", "郵寄")], max_length=50
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"db_table": "Category",},
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="GroupActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("type", models.CharField(max_length=50)),
                ("location", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("place_id", models.CharField(blank=True, max_length=200, null=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("deadline", models.DateField()),
                ("min_participants", models.IntegerField(default=1)),
                ("max_participants", models.IntegerField(default=10)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="group_activity_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact_info",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "團體活動",
                "verbose_name_plural": "團體活動",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="web_app.activitycomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="web_app.groupactivity",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"],},
        ),
        migrations.CreateModel(
            name="Book2",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[("new", "全新"), ("good", "良好"), ("used", "尚可")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("price", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book2_covers/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic",
                    models.ForeignKey(
                        blank=True,
                        db_column="academic_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_app.academic",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="book2_contact",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_column="department_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_app.department",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_app.academicgrade",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="book2_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="category_id",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_app.category",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_app.status",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("joined", "已加入"), ("cancelled", "已取消")],
                        default="joined",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="web_app.groupactivity",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "activity"), name="uniq_user_activity"
                    )
                ],
            },
        ),
    ]
