# Generated by Django 5.2 on 2025-08-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_app", "0004_fix_star_rating"),
        ("web_app", "0004_rename_rating_star_star_remove_coursereview_rating_and_more"),
    ]

    operations = []
